# Generated by Django 3.2.4 on 2021-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(default='13EBA', editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
