# Generated by Django 3.2.3 on 2021-05-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pizza', '0002_auto_20210530_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(default='BC3F9', editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='C953E', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ProductOrderID',
            field=models.CharField(default='14E26', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
