# Generated by Django 3.2.2 on 2021-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pizza', '0002_auto_20210523_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('ProductOrderID', models.CharField(default='471E1', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('size', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('toppings', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(default='5AEA4', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='73BD1', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
