# Generated by Django 3.2 on 2021-04-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pizza', '0002_auto_20210405_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', 'slug'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
